language: python
python:
- '3.6'
services:
  - redis-server
script: pytest tests/*
before_install:
- openssl aes-256-cbc -K $encrypted_7c83ef00f946_key -iv $encrypted_7c83ef00f946_iv
  -in conf/overrides.json.enc -out conf/overrides.json -d
